# --- App Info ---
spring.application.name=auth-core
server.port=8080

# --- JWT ---
application.security.jwt.secret-key=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.security.jwt.expiration=86400000

# --- Database ---
spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# ==========================================
# SMART KAFKA CONFIG (AIVEN READY)
# ==========================================

# 1. If KAFKA_URL isn't provided, default to localhost (won't crash app)
spring.kafka.bootstrap-servers=${KAFKA_URL:localhost:9092}

# 2. If KAFKA_PROTO isn't provided, default to PLAINTEXT (no SSL required)
spring.kafka.security.protocol=${KAFKA_PROTO:PLAINTEXT}

# 3. SSL CERTS (Smart Overwrites)
# If the environment variables are not present, these become EMPTY.
# Spring will NOT try to load a file if the path is empty.
spring.kafka.ssl.keystore-location=${KAFKA_KEY_PATH:}
spring.kafka.ssl.keystore-password=${KAFKA_KEY_PASS:}
spring.kafka.ssl.key-password=${KAFKA_KEY_PASS:}

spring.kafka.ssl.truststore-location=${KAFKA_TRUST_PATH:}
spring.kafka.ssl.truststore-password=${KAFKA_TRUST_PASS:}



# --------------------------------------------------------------------------
# AIVEN CLOUD TEMPLATE (Uncomment and fill to connect to Aiven)
# --------------------------------------------------------------------------
# spring.kafka.bootstrap-servers=${KAFKA_URL:your-aiven-url.aivencloud.com:12345}
# spring.kafka.security.protocol=${KAFKA_PROTO:SSL}
# Make sure your files are in src/main/resources/certs/
# spring.kafka.ssl.keystore-location=${KAFKA_KEY_PATH:classpath:certs/client.keystore.p12}
# spring.kafka.ssl.keystore-password=${KAFKA_KEY_PASS:your_aiven_password}
# spring.kafka.ssl.key-password=${KAFKA_KEY_PASS:your_aiven_password}
# spring.kafka.ssl.truststore-location=${KAFKA_TRUST_PATH:classpath:certs/client.truststore.jks}
# spring.kafka.ssl.truststore-password=${KAFKA_TRUST_PASS:your_aiven_password}



# ==========================================
# RESILIENCE (Critical for "No-Crash" Login)
# ==========================================
# If Kafka is down/unreachable, don't let the Login hang. 
# Give up trying to connect to Kafka after 2 seconds.
spring.kafka.producer.properties.max.block.ms=2000
spring.kafka.producer.acks=all
spring.kafka.producer.properties.delivery.timeout.ms=3000